language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install pyparsing==2.0.1"
  - "pip install pytest>=2.8.1"
# command to run tests
script: py.test system/tests --ignore=system/tests/data
